import { useCallback, useMemo, useState } from 'react';
import { mockExams as contentExams, mockQuestions, mockSubQuestions } from '@/mocks/mockData/content'; export type SourceType = 'exercise' | 'document';
export type CreateStep = 'start' | 'analysis' | 'generation';
export type Difficulty = 'auto' | 'basic' | 'standard' | 'applied' | 'difficult'; export type ExerciseOptionsState = { difficulty: Difficulty; useDiagrams: boolean; confirmStructure: boolean; isPublic: boolean;
}; export type DocumentFormatConfig = { isAuto: boolean; selectedFormats: string[];
}; export type DocumentOptionsState = { difficulty: Difficulty; questionCount: number; useDiagrams: boolean; confirmStructure: boolean; isPublic: boolean; formatConfig: DocumentFormatConfig;
}; const defaultExerciseOptions: ExerciseOptionsState = { difficulty: 'auto', useDiagrams: true, confirmStructure: false, isPublic: true,
}; const defaultDocumentOptions: DocumentOptionsState = { difficulty: 'auto', questionCount: 10, useDiagrams: true, confirmStructure: false, isPublic: true, formatConfig: { isAuto: true, selectedFormats: [], },
}; export function useProblemCreateFlow(initialSource: SourceType = 'exercise') { const [sourceType, setSourceType] = useState<SourceType>(initialSource); const [step, setStep] = useState<CreateStep>('start'); const [exerciseOptions, setExerciseOptions] = useState<ExerciseOptionsState>(defaultExerciseOptions); const [documentOptions, setDocumentOptions] = useState<DocumentOptionsState>(defaultDocumentOptions); const [examDraft, setExamDraft] = useState(() => { const baseExam = contentExams[0]; if (!baseExam) return { questions: [] } as any; const questions = mockQuestions .filter((q) => q.examId === baseExam.id)
)), })); return JSON.parse(JSON.stringify({ ...baseExam, questions })); }); const shouldConfirmStructure = useMemo( () => (sourceType === 'exercise' ? exerciseOptions.confirmStructure : documentOptions.confirmStructure), [sourceType, exerciseOptions.confirmStructure, documentOptions.confirmStructure]); const proceedFromStart = useCallback(() => { setStep(shouldConfirmStructure ? 'analysis' : 'generation'); }, [shouldConfirmStructure]); const goToAnalysis = useCallback(() => setStep('analysis'), []); const goToGeneration = useCallback(() => setStep('generation'), []); const backToStart = useCallback(() => setStep('start'), []); const backToAnalysis = useCallback(() => setStep('analysis'), []); const backFromGeneration = useCallback(() => { setStep(shouldConfirmStructure ? 'analysis' : 'start'); }, [shouldConfirmStructure]); return { sourceType, setSourceType, step, proceedFromStart, goToAnalysis, goToGeneration, backToStart, backToAnalysis, backFromGeneration, exerciseOptions, setExerciseOptions, documentOptions, setDocumentOptions, examDraft, setExamDraft, shouldConfirmStructure, };
}
