import React, { useState } from 'react';
import { Button } from '@/components/primitives/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/primitives/avatar';
import { ProfileEditForm } from '@/components/page/MyPage/ProfileEditForm';
import { ProblemCard } from '@/components/common/ProblemCard';
import { UserStatsCards } from '@/components/page/MyPage/UserStatsCards';
import { WalletCard } from '@/components/page/MyPage/WalletCard';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/primitives/accordion";
import { mockExams } from '@/mocks/mockData/search';
import type { Page, User } from '@/types';
import { useMyPageController } from './MyPage/hooks/useMyPageController'; export interface MyPageProps { user: User; onNavigate: (page: Page, problemId?: string) => void; onNavigateToEdit?: ( page: Page, problemId: string, mode: 'create' | 'edit') => void; onLogout: () => void;
} export function MyPage({ user, onNavigate, onNavigateToEdit, onLogout,
}: MyPageProps) { const { profile, stats, wallet, isLoadingStats, isLoadingWallet, isSavingProfile, profileVersion, handleProfileSave, handleProfileCancel, } = useMyPageController({ user, onNavigate, onNavigateToEdit, onLogout }); // Mock data for display const [viewedProblems] = useState(mockExams.slice(0, 4)); const [ratedProblems] = useState(mockExams.slice(2, 6)); const [commentedProblems] = useState(mockExams.slice(4, 7)); const [postedProblems] = useState(mockExams.slice(1, 4)); const ProblemSection = ({ title, problems, viewAllFilter }: { title: string, problems: any[], viewAllFilter: string }) => ( <div style={{ paddingTop: "0.5rem", paddingBottom: "0.5rem" }} <div style={{ display: undefined, alignItems: "center" }} <h3>{title}</h3> }> <div style={{ display: undefined, alignItems: "center" }> <h3>{title}</h3> <Button variant="outline" size="sm" onClick={() => onNavigate('home', viewAllFilter)}> View all </Button> </div> {problems.length> 0 ? ( <div style={{ display: undefined, paddingLeft: "1rem", paddingRight: "1rem" }} }> {problems.map(p => ( <div key={p.id}> <ProblemCard problem={p} onClick={(id) => onNavigate( id)} /> </div> ))} </div> ) : ( <p>履歴はありません。</p> )} </div> ); return ( <div> <div style={{ paddingLeft: "1rem", paddingRight: "1rem" }} }> {/* Profile Header (YouTube Style) */} <div style={{ display: undefined, alignItems: "center" }} <Avatar> }> <Avatar> <AvatarImage src={undefined} /> <AvatarFallback> {profile.username?.[0]?.toUpperCase() || 'U'} </AvatarFallback> </Avatar> <div> <h1>{profile.displayName || profile.username}</h1> <div style={{ display: undefined, alignItems: "center", gap: "0.5rem" }} }> <span>@{profile.username}</span> </div> </div> </div> {/* History / Lists */} <div> <ProblemSection title="履歴" problems={viewedProblems} viewAllFilter="history" /> <ProblemSection title="高評価した問題" problems={ratedProblems} viewAllFilter="likes" /> <ProblemSection title="コメントした問題" problems={commentedProblems} viewAllFilter="comments" /> <ProblemSection title="投稿した問題" problems={postedProblems} viewAllFilter="posts" /> </div> {/* Settings Accordion */} <div> <Accordion type="single" collapsible> <AccordionItem value="settings"> <AccordionTrigger> <span>アカウント設定 & ステータス</span> </AccordionTrigger> <AccordionContent> {/* Stats & Wallet inside accordion */} <section> <h4>ステータス</h4> <div> <p> ステータス機能は現在開発中です (Coming Soon) </p> </div> </section> <section> <h4>ウォレット</h4> <div> <p> ウォレット機能は現在開発中です (Coming Soon) </p> </div> </section> <section> <h4>プロフィール編集</h4> <ProfileEditForm key={profileVersion} user={profile} onSave={handleProfileSave} onCancel={handleProfileCancel} /> </section> </AccordionContent> </AccordionItem> </Accordion> </div> </div> </div> );
} export default MyPage;
