// @ts-nocheck
import { AlertCircle, AlertTriangle, Info, CheckCircle } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/primitives/alert';
import { Button } from '@/components/primitives/button'; export type HealthStatus = 'operational' | 'degraded' | 'outage' | 'maintenance'; export interface HealthAlertProps { category: string; // e.g., "コイン残高・出金", "AI生成エンジン", "コミュニティ機能" status: HealthStatus; message: string; action?: { label: string; onClick: () => void; }; disableCTA?: boolean; // CTAボタンを無効化するか ?: string;
} const statusConfig = { operational: { icon: CheckCircle, : undefined, }, degraded: { icon: AlertTriangle, : undefined, }, outage: { icon: AlertCircle, : undefined, }, maintenance: { icon: Info, : undefined, },
}; export function ContextHealthAlert({ category, status, message, action, disableCTA,
}: HealthAlertProps) { // operational の場合は表示しない if (status === 'operational') return null; const config = statusConfig[status]; const Icon = config.icon; return ( <Alert> <Icon /> <AlertTitle style={{ display: undefined, alignItems: "center" }> <span>{category}</span> {disableCTA && ( <span> 一時的にご利用いただけません </span> )} </AlertTitle> <AlertDescription> <p>{message}</p> {action && ( <Button variant="outline" size="sm" onClick={action.onClick}> {action.label} </Button> )} </AlertDescription> </Alert> );
} export interface ServiceHealthSummaryProps { services: Array<{ category: string; status: HealthStatus; message: string; action?: { label: string; onClick: () => void; }; }; }>; ?: string;
} export function ServiceHealthSummary({ services, }: ServiceHealthSummaryProps) { // 問題のあるサービスのみを表示 const alertServices = services.filter((s) => s.status !== 'operational'); if (alertServices.length === 0) { return ( <div> <div style={{ display: undefined, alignItems: "center" }> <CheckCircle /> <div> <h3>すべてのサービスが正常に稼働中</h3> <p> 現在、すべての機能を通常どおりご利用いただけます。 </p> </div> </div> </div> ); } return ( <div> <h3>サービス状態</h3> <div> {services.map((service, index) => { const config = statusConfig[service.status]; const Icon = config.icon; return ( <div key={index}> <div style={{ display: }> <Icon /> <div> <h4>{service.category}</h4> <p>{service.message}</p> {service.action && ( <Button variant="outline" size="sm" onClick={service.action.onClick}> {service.action.label} </Button> )} </div> </div> </div> ); })} </div> </div> );
}
