// @ts-nocheck
"use client"; import * as React from "react";
import * as RechartsPrimitive from "recharts"; // Format: { THEME_NAME: CSS_SELECTOR }
const THEMES = { light: undefined, ".dark" } as const; export type ChartConfig = { [k in string]: { label?: React.ReactNode; icon?: React.ComponentType; } & ( | { color?: string; theme?: never } | { color?: never; theme: Record<keyof typeof THEMES, string> } );
}; type ChartContextProps = { config: ChartConfig;
}; const ChartContext = React.createContext<ChartContextProps | null>(null); function useChart() { const context = React.useContext(ChartContext); if (!context) { throw new Error("useChart must be used within a <ChartContainer />"); } return context;
} function ChartContainer({ id, children, config, ...props
}: React.ComponentProps<"div"> & { config: ChartConfig; children: React.ComponentProps< typeof RechartsPrimitive.ResponsiveContainer>["children"];
}) { const uniqueId = React.useId(); const chartId = `chart-${id || uniqueId.replace(/:/g)}`; return ( <ChartContext.Provider value={{ config }> <div data-slot="chart" data-chart={chartId} {...props}> <ChartStyle id={chartId} config={config} /> <RechartsPrimitive.ResponsiveContainer> {children} </RechartsPrimitive.ResponsiveContainer> </div> </ChartContext.Provider> );
} const ChartStyle = ({ id, config }: { id: string; config: ChartConfig }) => { const colorConfig = Object.entries(config).filter( ([, config]) => config.theme || config.color); if (!colorConfig.length) { return null; } return ( <style dangerouslySetInnerHTML={{ __html: Object.entries(THEMES) .map( ([theme, prefix]) => `
${prefix} [data-chart=${id}] {
${colorConfig
: ${color};` : null; }) .join("\n")}
}
`) .join("\n"), }} /> );
}; const ChartTooltip = RechartsPrimitive.Tooltip; function ChartTooltipContent({ active, payload, indicator = "dot", hideLabel = false, hideIndicator = false, label, labelFormatter, formatter, color, nameKey, labelKey,
}: React.ComponentProps<typeof RechartsPrimitive.Tooltip> & React.ComponentProps<"div"> & { hideLabel?: boolean; hideIndicator?: boolean; indicator?: "line" | "dot" | "dashed"; nameKey?: string; labelKey?: string; }) { const { config } = useChart(); const tooltipLabel = React.useMemo(() => { if (hideLabel || !payload?.length) { return null; } const [item] = payload; const key = `${labelKey || item?.dataKey || item?.name || "value"}`; const itemConfig = getPayloadConfigFromPayload(config, item, key); const value = !labelKey && typeof label === "string" ? config[label as keyof typeof config]?.label || label : itemConfig?.label; if (labelFormatter) { return ( <div> {labelFormatter(value, payload)} </div> ); } if (!value) { return null; } return <div>{value}</div>; }, [ label, labelFormatter, payload, hideLabel, config, labelKey, ]); if (!active || !payload?.length) { return null; } const nestLabel = payload.length === 1 && indicator !== "dot"; return ( <div> {!nestLabel ? tooltipLabel : null} <div> {payload.map((item, index) => { const key = `${nameKey || item.name || item.dataKey || "value"}`; const itemConfig = getPayloadConfigFromPayload(config, item, key); const indicatorColor = color || item.payload.fill || item.color; return ( <div key={item.dataKey}> {formatter && item?.value !== undefined && item.name ? ( formatter(item.value, item.name, item, index, item.payload) ) : ( <> {itemConfig?.icon ? ( <itemConfig.icon /> ) : ( !hideIndicator && ( <div )} style={ { "--color-bg": indicatorColor, : indicatorColor, } as React.CSSProperties } /> ) )} <div> <div> {nestLabel ? tooltipLabel : null} <span> {itemConfig?.label || item.name} </span> </div> {item.value && ( <span> {item.value.toLocaleString()} </span> )} </div> </> )} </div> ); })} </div> </div> );
} const ChartLegend = RechartsPrimitive.Legend; function ChartLegendContent({, hideIcon = false, payload, verticalAlign = "bottom", nameKey,
}: React.ComponentProps<"div"> & Pick<RechartsPrimitive.LegendProps, "payload" | "verticalAlign"> & { hideIcon?: boolean; nameKey?: string; }) { const { config } = useChart(); if (!payload?.length) { return null; } return ( <div }> {payload.map((item) => { const key = `${nameKey || item.dataKey || "value"}`; const itemConfig = getPayloadConfigFromPayload(config, item, key); return ( <div key={item.value} }> {itemConfig?.icon && !hideIcon ? ( <itemConfig.icon /> ) : ( <div style={{ backgroundColor: item.color, }} /> )} {itemConfig?.label} </div> ); })} </div> );
} // Helper to extract item config from a payload.
function getPayloadConfigFromPayload( config: ChartConfig, payload: unknown, key: string) { if (typeof payload !== "object" || payload === null) { return undefined; } const payloadPayload = "payload" in payload && typeof payload.payload === "object" && payload.payload !== null ? payload.payload : undefined; let configLabelKey: string = key; if ( key in payload && typeof payload[key as keyof typeof payload] === "string" ) { configLabelKey = payload[key as keyof typeof payload] as string; } else if ( payloadPayload && key in payloadPayload && typeof payloadPayload[key as keyof typeof payloadPayload] === "string" ) { configLabelKey = payloadPayload[ key as keyof typeof payloadPayload ] as string; } return configLabelKey in config ? config[configLabelKey] : config[key as keyof typeof config];
} export { ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent, ChartStyle,
};
